// Single source of truth for all site copy. Every user-facing string exists in
// both languages; the build renders /index.html (es) and /en/index.html (en).

export const site = {
  url: 'https://adrgarcia.com',
  name: 'Adrián García Juárez',
  email: 'gadrianjua@gmail.com',
  linkedin: 'https://www.linkedin.com/in/adrian-garcia-juarez-83020b232',
  locales: ['es', 'en'],
};

export const t = {
  es: {
    htmlLang: 'es-MX',
    ogLocale: 'es_MX',
    path: '/',
    title: 'Adrián García Juárez — Cloud Solutions Architect · Google Cloud',
    description:
      'Cloud Solutions Architect con 6 certificaciones vigentes de Google Cloud. Más de 4 años y medio implementando nube y convirtiendo necesidades de negocio en propuestas para empresas de México y Latinoamérica. CDMX, disponible para nuevas oportunidades.',
    skip: 'Saltar al contenido',
    nav: { about: 'Perfil', experience: 'Experiencia', certs: 'Certificaciones', skills: 'Habilidades', contact: 'Contacto' },
    menu: 'Menú',
    langSwitch: { label: 'English', short: 'EN', aria: 'Ver el sitio en inglés' },
    theme: { toLight: 'Cambiar a tema claro', toDark: 'Cambiar a tema oscuro' },
    hero: {
      role: 'Cloud Solutions Architect',
      status: 'Disponible para nuevas oportunidades',
      tagline: 'Implemento soluciones en la nube y las convierto en propuestas de negocio.',
      lede: 'Más de cuatro años y medio entre la consola y la sala de juntas: escucho la necesidad de la empresa, diseño la arquitectura en Google Cloud y la presento con costos y ROI claros.',
      ctaPrimary: 'Escríbeme',
      ctaLinkedin: 'LinkedIn',
      proof: '6 certificaciones Google Cloud vigentes',
      proofDetail: '3 Professional · 1 Associate · 2 Foundational',
      location: 'Ciudad de México',
      photoAlt: 'Adrián García Juárez sonriendo, de pie en un sendero bajo los toriis rojos de un santuario en Kioto, Japón.',
    },
    about: {
      title: 'Perfil',
      body: [
        'Soy Ingeniero en Informática egresado del Instituto Politécnico Nacional (UPIICSA) y arquitecto de soluciones certificado en Google Cloud. Empecé implementando infraestructura en GCP con mis propias manos y después pasé a la preventa y a la estrategia técnica comercial. Esa mezcla es mi diferencial: sé lo que cuesta construir una solución y sé cómo defenderla ante negocio.',
        'Escucho el problema de cada empresa, lo traduzco en requerimientos y lo convierto en una propuesta de negocio con arquitectura, costos (FinOps) y retorno claros. Así la decisión es más fácil y el cierre, más rápido.',
      ],
      pillars: [
        {
          icon: 'cloud',
          color: 'green',
          title: 'Implementación en la nube',
          body: 'Despliego y automatizo infraestructura, datos, seguridad e IA en Google Cloud con Terraform, CI/CD y buenas prácticas de IAM. También conozco AWS y Azure.',
          chips: ['Google Cloud', 'AWS', 'Azure', 'Terraform'],
        },
        {
          icon: 'briefcase',
          color: 'pink',
          title: 'De la necesidad a la propuesta',
          body: 'Hago el discovery, diseño la solución, la valido con una prueba de concepto y la presento con costos y ROI en el idioma de quien decide.',
          chips: ['Discovery', 'PoCs', 'FinOps', 'ROI'],
        },
        {
          icon: 'globe',
          color: 'blue',
          title: 'Industrias y mercados',
          body: 'De micro SMB a Enterprise, pasando por SMB y Corporate, en México y Latinoamérica: Colombia, Perú y Ecuador.',
          chips: ['TI', 'Healthcare', 'Retail', 'E-commerce', 'Finanzas', 'Industria'],
        },
      ],
      facts: [
        { k: 'Base', v: 'CDMX, México' },
        { k: 'Formación', v: 'Ing. en Informática · UPIICSA-IPN, 2022' },
        { k: 'Idiomas', v: 'Español nativo · Inglés C1' },
        { k: 'Enfoque', v: 'Infraestructura, Datos, Seguridad e IA' },
      ],
      sceneAlt: 'Adrián en un bosque de coníferas bajo cielo despejado.',
    },
    exp: {
      title: 'Experiencia',
      scope: { segments: 'Segmentos', industries: 'Industrias', countries: 'Países', stack: 'Alcance' },
      intro: 'De la infraestructura a la estrategia técnica comercial. Selecciona un puesto para ver el detalle.',
      present: 'Actualidad',
      total: 'años de experiencia',
      since: 'desde',
      start: 'Inicio',
      today: 'Hoy',
      tenure: 'en la empresa',
      yearsWord: 'años',
      more: 'Ver logros',
      less: 'Ocultar logros',
      education: 'Formación',
    },
    certs: {
      title: 'Certificaciones',
      intro: 'Seis credenciales oficiales de Google Cloud, todas vigentes. Haz clic en cualquier tarjeta para ver la verificación pública en Credly.',
      verify: 'Verificar en Credly',
      view: 'Ver certificado',
      issued: 'Emitida',
      expires: 'Vigente hasta',
      newTab: '(se abre en una pestaña nueva)',
      levels: { professional: 'Professional', associate: 'Associate', foundational: 'Foundational' },
    },
    skills: { title: 'Habilidades' },
    contact: {
      title: '¿Buscas un Cloud Solutions Architect?',
      body: 'Estoy disponible para nuevas oportunidades en arquitectura cloud, preventa técnica o Customer Engineering. Escríbeme a mi correo o por LinkedIn; respondo en español o inglés.',
      email: 'Escríbeme',
      gmail: 'Redactar en Gmail',
      copy: 'Copiar correo',
      copied: 'Correo copiado',
      linkedin: 'LinkedIn',
      subject: 'Oportunidad para Adrián García — Cloud Solutions Architect',
      mailBody: 'Hola Adrián,\n\n',
    },
    viewer: {
      close: 'Cerrar',
      download: 'Descargar PDF',
      open: 'Abrir PDF',
      prev: 'Página anterior',
      next: 'Página siguiente',
      page: 'Página',
      of: 'de',
      zoom: 'Ampliar',
    },
    footer: { rights: 'Adrián García Juárez', built: 'Servido desde Google Cloud Run.', top: 'Volver arriba' },
    notFound: {
      title: 'Página no encontrada',
      body: 'Este camino no lleva a ningún lado; la dirección no existe o cambió de lugar. Estos sí te llevan a algún sitio:',
      back: 'Volver al inicio',
      links: { experience: 'Ver mi experiencia', certs: 'Ver certificaciones', contact: 'Escribirme un correo' },
    },
    months: ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'],
    dur: { y: 'año', ys: 'años', m: 'mes', ms: 'meses' },
  },
  en: {
    htmlLang: 'en',
    ogLocale: 'en_US',
    path: '/en/',
    title: 'Adrián García Juárez — Cloud Solutions Architect · Google Cloud',
    description:
      'Cloud Solutions Architect holding 6 active Google Cloud certifications. 4.5+ years implementing cloud and turning business needs into proposals for companies across Mexico and Latin America. Mexico City, open to new opportunities.',
    skip: 'Skip to content',
    nav: { about: 'Profile', experience: 'Experience', certs: 'Certifications', skills: 'Skills', contact: 'Contact' },
    menu: 'Menu',
    langSwitch: { label: 'Español', short: 'ES', aria: 'View the site in Spanish' },
    theme: { toLight: 'Switch to light theme', toDark: 'Switch to dark theme' },
    hero: {
      role: 'Cloud Solutions Architect',
      status: 'Open to new opportunities',
      tagline: 'I implement cloud solutions and turn them into business proposals.',
      lede: 'Over four and a half years between the console and the boardroom: I listen to what the business needs, design the Google Cloud architecture and present it with clear costs and ROI.',
      ctaPrimary: 'Get in touch',
      ctaLinkedin: 'LinkedIn',
      proof: '6 active Google Cloud certifications',
      proofDetail: '3 Professional · 1 Associate · 2 Foundational',
      location: 'Mexico City',
      photoAlt: 'Adrián García Juárez smiling, standing on a path beneath the red torii gates of a shrine in Kyoto, Japan.',
    },
    about: {
      title: 'Profile',
      body: [
        'I am an Informatics Engineer from Mexico’s Instituto Politécnico Nacional (UPIICSA) and a Google Cloud certified solutions architect. I started out implementing GCP infrastructure hands-on, then moved into presales and technical sales strategy. That mix is what sets me apart: I know what it takes to build a solution and how to make the case for it to the business.',
        'I listen to each company’s problem, translate it into requirements and turn it into a business proposal with clear architecture, costs (FinOps) and return. The decision gets easier and the deal closes faster.',
      ],
      pillars: [
        {
          icon: 'cloud',
          color: 'green',
          title: 'Hands-on cloud implementation',
          body: 'I deploy and automate infrastructure, data, security and AI on Google Cloud with Terraform, CI/CD and IAM best practices. I also work with AWS and Azure.',
          chips: ['Google Cloud', 'AWS', 'Azure', 'Terraform'],
        },
        {
          icon: 'briefcase',
          color: 'pink',
          title: 'From business need to proposal',
          body: 'I run discovery, design the solution, prove it with a proof of concept and present it with costs and ROI in the language of whoever signs off.',
          chips: ['Discovery', 'PoCs', 'FinOps', 'ROI'],
        },
        {
          icon: 'globe',
          color: 'blue',
          title: 'Industries & markets',
          body: 'From micro SMB to Enterprise, including SMB and Corporate, across Mexico and Latin America: Colombia, Peru and Ecuador.',
          chips: ['IT', 'Healthcare', 'Retail', 'E-commerce', 'Finance', 'Industry'],
        },
      ],
      facts: [
        { k: 'Based in', v: 'Mexico City, Mexico' },
        { k: 'Education', v: 'B.Sc. Computer Science · UPIICSA-IPN, 2022' },
        { k: 'Languages', v: 'Spanish (native) · English C1' },
        { k: 'Focus', v: 'Infrastructure, Data, Security & AI' },
      ],
      sceneAlt: 'Adrián in a conifer forest under a clear sky.',
    },
    exp: {
      title: 'Experience',
      scope: { segments: 'Segments', industries: 'Industries', countries: 'Countries', stack: 'Scope' },
      intro: 'From infrastructure to technical sales strategy. Select a role to see the details.',
      present: 'Present',
      total: 'years of experience',
      since: 'since',
      start: 'Start',
      today: 'Today',
      tenure: 'at the company',
      yearsWord: 'yrs',
      more: 'Show results',
      less: 'Hide results',
      education: 'Education',
    },
    certs: {
      title: 'Certifications',
      intro: 'Six official Google Cloud credentials, all active. Click any card to see its public verification on Credly.',
      verify: 'Verify on Credly',
      view: 'View certificate',
      issued: 'Issued',
      expires: 'Valid until',
      newTab: '(opens in a new tab)',
      levels: { professional: 'Professional', associate: 'Associate', foundational: 'Foundational' },
    },
    skills: { title: 'Skills' },
    contact: {
      title: 'Looking for a Cloud Solutions Architect?',
      body: 'I am open to new opportunities in cloud architecture, technical presales or Customer Engineering. Reach me by email or on LinkedIn; I reply in English or Spanish.',
      email: 'Email me',
      gmail: 'Compose in Gmail',
      copy: 'Copy email',
      copied: 'Email copied',
      linkedin: 'LinkedIn',
      subject: 'Opportunity for Adrián García — Cloud Solutions Architect',
      mailBody: 'Hi Adrián,\n\n',
    },
    viewer: {
      close: 'Close',
      download: 'Download PDF',
      open: 'Open PDF',
      prev: 'Previous page',
      next: 'Next page',
      page: 'Page',
      of: 'of',
      zoom: 'Zoom',
    },
    footer: { rights: 'Adrián García Juárez', built: 'Served from Google Cloud Run.', top: 'Back to top' },
    notFound: {
      title: 'Page not found',
      body: 'This path leads nowhere; the address does not exist or has moved. These ones do go somewhere:',
      back: 'Back to home',
      links: { experience: 'See my experience', certs: 'See certifications', contact: 'Send me an email' },
    },
    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    dur: { y: 'yr', ys: 'yrs', m: 'mo', ms: 'mos' },
  },
};

// Grouped by employer, newest first. Dates are ISO "YYYY-MM"; end null = present.
export const experience = [
  {
    company: 'Xertica.ai',
    logo: 'xertica',
    color: 'green',
    invertOnDark: true,
    roles: [
      {
        id: 'xertica-ce',
        start: '2026-06',
        end: '2026-09',
        title: { es: 'Customer Engineer', en: 'Customer Engineer' },
        summary: {
          es: 'Soluciones de Datos en Google Cloud para clientes del segmento Corporate.',
          en: 'Google Cloud Data solutions for Corporate-segment customers.',
        },
        scope: {
          segments: { es: 'Corporate', en: 'Corporate' },
          stack: { es: 'Soluciones de Datos en GCP', en: 'Data solutions on GCP' },
        },
        points: {
          es: [
            'Diseñé soluciones de **datos en Google Cloud** (data warehouse, pipelines y analítica) a partir de las necesidades de negocio de clientes Corporate.',
            'Desarrollé y presenté **pruebas de concepto** y demos en vivo que validan la factibilidad de la arquitectura ante tomadores de decisión.',
            'Trabajé a diario con ventas para destrabar objeciones técnicas, validar requerimientos y avanzar oportunidades en el pipeline.',
          ],
          en: [
            'Designed **Google Cloud data solutions** (data warehousing, pipelines and analytics) from the business needs of Corporate customers.',
            'Built and delivered hands-on **proofs of concept** and live demos that validate architectural feasibility for client decision-makers.',
            'Partnered daily with sales to unblock technical objections, validate requirements and move deals through the pipeline.',
          ],
        },
        tags: ['BigQuery', 'Data', 'PoCs', 'Discovery'],
      },
    ],
  },
  {
    company: 'Servinformación',
    logo: 'servinformacion',
    logoDark: true,
    color: 'blue',
    invertOnDark: false,
    roles: [
      {
        id: 'servi-tsl',
        start: '2024-11',
        end: '2026-04',
        title: { es: 'Technical Sales Leader México', en: 'Technical Sales Leader Mexico' },
        summary: {
          es: 'Estrategia técnica comercial en Google Cloud, con foco en soluciones Enterprise para México y Latinoamérica.',
          en: 'Technical sales strategy on Google Cloud, focused on Enterprise solutions across Mexico and Latin America.',
        },
        scope: {
          segments: { es: 'Micro SMB, SMB, Corporate y Enterprise', en: 'Micro SMB, SMB, Corporate and Enterprise' },
          industries: { es: 'Retail, Healthcare, Industria', en: 'Retail, Healthcare, Industry' },
          countries: { es: 'México y Latinoamérica', en: 'Mexico and Latin America' },
          stack: { es: 'Todo GCP: infraestructura, datos, seguridad e IA', en: 'All of GCP: infrastructure, data, security and AI' },
        },
        points: {
          es: [
            '**+38 %** de utilidad anual del negocio liderando la estrategia técnica y propuestas de alto valor en GCP.',
            '**≈ USD 260 k+** en upsell en cuentas clave al detectar oportunidades de modernización, como migraciones a BigQuery.',
            '**+10 %** en tasa de cierre al rediseñar las demos técnicas alrededor de resultados de negocio para audiencias C-Level.',
          ],
          en: [
            '**+38%** annual business utility by leading technical strategy and high-value proposals on GCP.',
            '**≈ USD 260k+** in upsell revenue across key accounts by spotting modernization opportunities such as BigQuery migrations.',
            '**+10%** deal closure rate by redesigning technical demos around business outcomes for C-level audiences.',
          ],
        },
        tags: ['BigQuery', 'Upsell', 'C-Level'],
      },
      {
        id: 'servi-presales',
        start: '2024-01',
        end: '2024-11',
        title: { es: 'Presales Engineer', en: 'Presales Engineer' },
        summary: {
          es: 'Preventa técnica de micro SMB a Corporate, cada vez más enfocada en soluciones Enterprise.',
          en: 'Technical presales from micro SMB to Corporate, increasingly focused on Enterprise solutions.',
        },
        scope: {
          segments: { es: 'Micro SMB, SMB, Corporate y Enterprise', en: 'Micro SMB, SMB, Corporate and Enterprise' },
          industries: { es: 'Retail, Healthcare, Industria', en: 'Retail, Healthcare, Industry' },
          countries: { es: 'México y Latinoamérica', en: 'Mexico and Latin America' },
          stack: { es: 'Todo GCP: infraestructura, datos, seguridad e IA', en: 'All of GCP: infrastructure, data, security and AI' },
        },
        points: {
          es: [
            '**+42 %** de utilidad anual para el área de preventa.',
            '**≈ 40 %** menos tiempo de ciclo de venta gracias a sesiones de discovery eficientes y PoCs de alto impacto.',
            'Pipeline técnico de **USD 380 k+** gestionado junto a los equipos comerciales.',
            '**80+** propuestas técnicas a la medida (Infra, Datos, Analítica) con **20 %** de tasa de éxito.',
          ],
          en: [
            '**+42%** annual utility for the presales department.',
            '**≈ 40%** shorter sales cycle through efficient discovery sessions and high-impact PoCs.',
            'Managed a technical pipeline worth **USD 380k+** alongside the sales teams.',
            '**80+** custom technical proposals (Infra, Data, Analytics) with a **20%** win rate.',
          ],
        },
        tags: ['Presales', 'PoCs', 'ROI'],
      },
    ],
  },
  {
    company: 'Xertica.ai',
    logo: 'xertica',
    color: 'green',
    invertOnDark: true,
    roles: [
      {
        id: 'xertica-analyst',
        start: '2023-01',
        end: '2023-12',
        title: { es: 'Cloud Analyst', en: 'Cloud Analyst' },
        summary: {
          es: 'Diseño y despliegue de infraestructura y monitoreo para nuevos clientes.',
          en: 'Designed and deployed infrastructure and monitoring for new customers.',
        },
        scope: {
          segments: { es: 'SMB y Corporate', en: 'SMB and Corporate' },
          industries: { es: 'Healthcare y Finanzas', en: 'Healthcare and Finance' },
          countries: { es: 'México, Colombia, Ecuador y Perú', en: 'Mexico, Colombia, Ecuador and Peru' },
          stack: { es: 'Infraestructura en GCP', en: 'GCP infrastructure' },
        },
        points: {
          es: [
            '**10–15 %** menos en la factura mensual de **15+** arquitecturas empresariales mediante FinOps y right-sizing.',
            '**30 %** menos tiempo de despliegue automatizando aprovisionamiento con **Terraform y Jenkins**, con consistencia total entre ambientes.',
            'IAM y buenas prácticas de seguridad integradas en cada despliegue para reducir la superficie de ataque.',
          ],
          en: [
            '**10–15%** lower monthly billing across **15+** enterprise architectures through FinOps and right-sizing.',
            '**30%** faster deployments by automating provisioning with **Terraform and Jenkins**, fully consistent across environments.',
            'Built IAM and security best practices into every deployment to shrink the attack surface.',
          ],
        },
        tags: ['FinOps', 'Terraform', 'IAM'],
      },
      {
        id: 'xertica-academy',
        start: '2022-02',
        end: '2023-01',
        title: { es: 'Academy Infra', en: 'Academy Infra' },
        summary: {
          es: 'Aprovisionamiento de servicios core de Google Cloud y soporte a clientes.',
          en: 'Provisioned core Google Cloud services and supported customers.',
        },
        scope: {
          segments: { es: 'SMB y Corporate', en: 'SMB and Corporate' },
          industries: { es: 'Healthcare y Finanzas', en: 'Healthcare and Finance' },
          countries: { es: 'México, Colombia, Ecuador y Perú', en: 'Mexico, Colombia, Ecuador and Peru' },
          stack: { es: 'Infraestructura en GCP', en: 'GCP infrastructure' },
        },
        points: {
          es: [
            'Onboarding de **20+** proyectos cloud con Compute Engine, VPC y Cloud Storage, priorizando alta disponibilidad.',
            'Gestión del ciclo de vida de tickets de soporte GCP, reduciendo tiempos de resolución.',
            'Biblioteca de **20+** documentos de arquitectura que estandarizó los despliegues del equipo.',
            'Sesiones de transferencia de conocimiento para que los equipos de los clientes operaran sus entornos.',
          ],
          en: [
            'Onboarded **20+** cloud projects on Compute Engine, VPC and Cloud Storage with a focus on high availability.',
            'Managed the GCP support ticket lifecycle, cutting incident resolution times.',
            'Wrote a library of **20+** architecture documents that standardized team deployments.',
            'Led knowledge-transfer sessions so client teams could run their own environments.',
          ],
        },
        tags: ['Compute Engine', 'VPC', 'Docs'],
      },
    ],
  },
];

export const education = {
  logo: 'ipn',
  logoDark: true,
  color: 'orange',
  school: 'UPIICSA · Instituto Politécnico Nacional',
  year: '2022',
  degree: { es: 'Ingeniería en Informática', en: 'B.Sc. Computer Science (Informatics Engineering)' },
};

// Ordered by level. Dates from the official certificate PDFs.
export const certifications = [
  {
    slug: 'professional-cloud-architect',
    desc: {
      es: 'Diseña arquitecturas seguras, escalables y de alta disponibilidad en Google Cloud, alineadas a objetivos de negocio.',
      en: 'Designs secure, scalable, highly available Google Cloud architectures aligned with business goals.',
    },
    name: 'Professional Cloud Architect',
    level: 'professional',
    issued: '2023-02-24',
    expires: '2027-02-21',
    credly: 'https://www.credly.com/badges/b7139028-a123-4fa7-b611-d6705fae6491/public_url',
  },
  {
    slug: 'professional-data-engineer',
    desc: {
      es: 'Diseña y opera plataformas de datos: pipelines, data warehouse en BigQuery, gobernanza y ML.',
      en: 'Designs and runs data platforms: pipelines, BigQuery warehousing, governance and ML.',
    },
    name: 'Professional Data Engineer',
    level: 'professional',
    issued: '2024-12-20',
    expires: '2026-12-20',
    credly: 'https://www.credly.com/badges/1972f535-bfde-4b3b-adc8-c7c2aa7ed48f/public_url',
  },
  {
    slug: 'professional-cloud-security-engineer',
    desc: {
      es: 'Protege cargas en Google Cloud: IAM, redes seguras, protección de datos y cumplimiento.',
      en: 'Secures Google Cloud workloads: IAM, network security, data protection and compliance.',
    },
    name: 'Professional Cloud Security Engineer',
    level: 'professional',
    issued: '2023-12-08',
    expires: '2027-11-14',
    credly: 'https://www.credly.com/badges/a719b6d7-e994-4441-85d0-50362c2fa8f6/public_url',
  },
  {
    slug: 'associate-cloud-engineer',
    desc: {
      es: 'Despliega, monitorea y opera proyectos y servicios de Google Cloud en el día a día.',
      en: 'Deploys, monitors and operates Google Cloud projects and services day to day.',
    },
    name: 'Associate Cloud Engineer',
    level: 'associate',
    issued: '2022-12-18',
    expires: '2027-09-01',
    credly: 'https://www.credly.com/badges/acb59d50-2bba-4ca5-8291-b61590d0e328/public_url',
  },
  {
    slug: 'generative-ai-leader',
    desc: {
      es: 'Estrategia de IA generativa: casos de uso, agentes y adopción responsable en la empresa.',
      en: 'Generative AI strategy: use cases, agents and responsible adoption in the enterprise.',
    },
    name: 'Generative AI Leader',
    level: 'foundational',
    issued: '2026-04-23',
    expires: '2029-04-23',
    credly: 'https://www.credly.com/badges/605fa181-ffb9-4a09-8057-93e7c478ce2a/public_url',
  },
  {
    slug: 'cloud-digital-leader',
    desc: {
      es: 'Explica el valor de la nube y la transformación digital con Google Cloud en términos de negocio.',
      en: 'Explains cloud value and digital transformation with Google Cloud in business terms.',
    },
    name: 'Cloud Digital Leader',
    level: 'foundational',
    issued: '2023-06-24',
    expires: '2029-05-15',
    credly: 'https://www.credly.com/badges/8033759b-aced-4098-8db8-5702797b3fda/public_url',
  },
];

export const skills = [
  {
    title: { es: 'Multicloud y DevOps', en: 'Multicloud & DevOps' },
    items: ['Google Cloud Platform', 'AWS', 'Microsoft Azure', 'Terraform', 'Docker', 'Kubernetes', 'Linux', 'Jenkins', 'CI/CD', { es: 'Redes on-premises', en: 'On-prem networking' }],
  },
  {
    title: { es: 'Datos e IA', en: 'Data & AI' },
    items: [
      'BigQuery',
      { es: 'Propuestas de Data Warehouse', en: 'Data warehouse proposals' },
      { es: 'Gobernanza de datos', en: 'Data governance' },
      { es: 'ETL y flujos de datos', en: 'ETL & data workflows' },
      'MySQL',
      'PostgreSQL',
      'SQL Server',
      { es: 'Agentes con ADK (Agent Development Kit)', en: 'Agents with ADK (Agent Development Kit)' },
      { es: 'Protocolo A2A (Agent2Agent)', en: 'A2A protocol (Agent2Agent)' },
      { es: 'Arquitectura de agentes de IA', en: 'AI agent architecture' },
    ],
  },
  {
    title: { es: 'Desarrollo', en: 'Development' },
    items: ['Python', 'JavaScript', 'Node.js', 'React', 'HTML / CSS', 'Git / GitHub'],
  },
  {
    title: { es: 'Negocio y productividad', en: 'Business & productivity' },
    items: [
      { es: 'Propuestas de negocio', en: 'Business proposals' },
      { es: 'Discovery de necesidades', en: 'Needs discovery' },
      { es: 'Preventa técnica', en: 'Technical presales' },
      'FinOps',
      { es: 'Pruebas de concepto', en: 'Proofs of concept' },
      { es: 'Admin. de Google Workspace', en: 'Google Workspace admin' },
      'AppSheet (no-code)',
      { es: 'Microsoft 365 (básico)', en: 'Microsoft 365 (baseline)' },
    ],
  },
];
